const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');
const base=process.env.QUIZ_TEST_URL;
assert(['127.0.0.1','localhost'].includes(new URL(base).hostname));
const fixture=JSON.parse(fs.readFileSync(process.env.QUIZ_HISTORY_FIXTURE,'utf8'));
assert(fixture.syntheticOnly);
const output=process.env.QUIZ_BROWSER_OUTPUT || 'output/playwright/history';fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
try{for(const width of [1440,390]){
 const context=await browser.newContext({viewport:{width,height:900},isMobile:width<640});const page=await context.newPage();const errors=[];
 page.on('pageerror',()=>errors.push('pageerror'));
 await page.goto(base+'/ops/');await page.locator('[name=username]').fill(fixture.username);await page.locator('[name=password]').fill(fixture.password);
 await Promise.all([page.waitForURL(base+'/ops/'),page.locator('button[type=submit]').click()]);
 await page.getByRole('link',{name:'查看测试历史（只读）'}).click();
 assert.equal(await page.locator('[data-history-readonly]').count(),1);
 await page.locator(`a[href="/ops/history/activities/${fixture.activityId}/"]`).click();
 assert.equal(await page.locator('#historyParticipants tr').count(),50);
 await page.getByRole('button',{name:'下一页',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('#historyParticipants tr').length===2);
 await page.locator('[name=display_name]').fill('同名样例');
 await page.getByRole('button',{name:'检索',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('#historyParticipants tr').length===2 && document.querySelector('[name=display_name]').value==='同名样例');
 assert(!page.url().includes('display_name'));assert(!page.url().includes('同名'));
 assert.equal(await page.locator('[data-invalidate-url], [name=status], [data-deidentify-url]').count(),0);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:`${output}/history-${width}.png`,mask:[page.locator('#historyParticipants'),page.locator('[name=display_name]')]});
 await page.locator(`a[href="/ops/history/activities/${fixture.activityId}/participants/${fixture.participantId}/"]`).first().click();
 assert.equal(await page.locator('[data-history-readonly]').count(),1);
 assert.equal(await page.locator('.attempt-record').count(),25);
 await page.locator('details summary').first().click();
 assert.equal(await page.locator('.submitted-answer img').count(),0);
 assert.equal(await page.evaluate(()=>window.badAnswer),undefined);
 await page.screenshot({path:`${output}/detail-${width}.png`,mask:[page.locator('.hero-window h2'),page.locator('.submitted-answer'),page.locator('.mono')]});
 await page.getByRole('link',{name:'下一页',exact:true}).click();assert.equal(await page.locator('.attempt-record').count(),2);
 await page.getByRole('link',{name:'返回测试历史'}).click();
 assert(page.url().includes('/ops/history/'));
 assert.deepEqual(errors,[]);results.push({width,passed:true,checks:['formal login','history link','52-person pagination','POST search','27-attempt pagination','escaped answers','read-only controls','no overflow']});
 await context.close();console.log(`History viewport ${width}: passed`);
}fs.writeFileSync(`${output}/results.json`,JSON.stringify(results,null,2));}finally{await browser.close();}})().catch(error=>{console.error(String(error.message).split('Call log:')[0]);process.exit(1);});
