const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.QUIZ_TEST_URL;
assert.equal(new URL(base).hostname, '127.0.0.1');
const fixture = JSON.parse(fs.readFileSync(process.env.QUIZ_REFRESH_FIXTURE, 'utf8'));
assert(fixture.syntheticOnly);
const output = 'output/playwright/refresh'; fs.mkdirSync(output, {recursive:true});
const wait = async (check) => { for(let i=0;i<100;i++){if(await check())return;await new Promise(r=>setTimeout(r,100));}throw new Error('Condition timed out'); };
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
 try{for(const width of [1440,390]){
  const context=await browser.newContext({viewport:{width,height:900},isMobile:width<640});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/ops/');await page.locator('[name=username]').fill(fixture.username);await page.locator('[name=password]').fill(fixture.password);
  await Promise.all([page.waitForURL(base+'/ops/'),page.locator('button[type=submit]').click()]);
  const url=base+`/ops/activities/${fixture.activityId}/`;
  await page.goto(url);await page.clock.install();
  assert.equal(await page.locator('#participantRows tr').count(),50);
  let responses=0;let fail=false;
  await page.route(url,async route=>{
   responses++;
   if(fail)return route.fulfill({status:503,body:'unavailable'});
   const response=await route.fetch();let html=await response.text();
   html=html.replace('<tbody id="recentAttemptRows" data-refresh-region>','<tbody id="recentAttemptRows" data-refresh-region><tr data-refresh-test><td colspan="7">刷新批次 '+responses+'</td></tr>');
   await route.fulfill({response,body:html});
  });
  const refresh=async()=>{const before=responses;await page.locator('#opsRefreshNow').click();await wait(async()=>responses>before && (await page.locator('#opsRefreshStatus').textContent()).startsWith('已更新'));};
  await refresh();assert.equal(await page.locator('[data-refresh-test]').count(),1);
  await page.locator('#participantRows .participant-select').first().uncheck();
  const unchecked=await page.locator('#participantRows tr').first().getAttribute('data-participant-id');
  await refresh();assert.equal(await page.locator(`[data-participant-id="${unchecked}"] .participant-select`).isChecked(),false);
  await page.locator('#participantSearch [name=display_name]').fill('同名样例');
  await page.locator('#participantSearch button[type=submit]').click();
  await wait(async()=>await page.locator('#participantRows tr').count()===2);
  await refresh();assert.equal(await page.locator('#participantSearch [name=display_name]').inputValue(),'同名样例');
  assert.equal(await page.locator('#participantRows tr').count(),2);
  await page.locator('#participantSearch [name=display_name]').fill('');
  await page.locator('#participantSearch button[type=submit]').click();
  await wait(async()=>await page.locator('#participantRows tr').count()===50);
  await page.locator('[data-participant-page=next]').click();
  await wait(async()=>await page.locator('#participantRows tr').count()===2);
  const pagination=await page.locator('#participantPageStatus').textContent();
  await page.locator('[data-reveal=identifier]').click();
  await wait(async()=>await page.locator('[data-reveal=identifier]').getAttribute('data-active')==='true');
  const revealed=responses;await page.locator('#opsRefreshNow').click();
  assert.equal(responses,revealed);assert((await page.locator('#opsRefreshStatus').textContent()).includes('完整身份'));
  await page.locator('[data-reveal=identifier]').click();
  const reason=page.locator('#activityControls input[name=reason]').first();await reason.fill('保留操作草稿');
  await refresh();assert.equal(await reason.inputValue(),'保留操作草稿');assert.equal(await page.locator('#participantPageStatus').textContent(),pagination);
  const before=responses;await page.clock.fastForward(31000);await wait(async()=>responses>before && (await page.locator('#opsRefreshStatus').textContent()).startsWith('已更新'));
  await reason.focus();const typing=responses;await page.clock.fastForward(31000);assert.equal(responses,typing);
  await page.locator('#opsAutoRefresh').uncheck();await page.clock.fastForward(61000);assert.equal(responses,typing);
  fail=true;await page.locator('#opsRefreshNow').click();await wait(async()=>(await page.locator('#opsRefreshStatus').textContent()).includes('刷新失败'));
  assert.equal(await page.locator('#participantRows tr').count(),2);assert.equal(await reason.inputValue(),'保留操作草稿');
  fail=false;await refresh();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:`${output}/console-${width}.png`,mask:[page.locator('#participantRows'),page.locator('#recentAttemptRows')]});
  const detail=base+`/ops/activities/${fixture.activityId}/participants/${fixture.participantId}/`;
  await page.goto(detail);assert.equal(await page.locator('.attempt-record').count(),25);
  await page.locator('details summary').first().click();const record=await page.locator('.attempt-record').first().getAttribute('id');
  await page.locator('#opsRefreshNow').click();await wait(async()=>(await page.locator('#opsRefreshStatus').textContent()).startsWith('已更新'));
  assert(await page.locator(`#${record} details`).getAttribute('open')!==null);
  await page.getByRole('link',{name:'下一页',exact:true}).click();assert.equal(await page.locator('.attempt-record').count(),2);
  await page.locator('#opsRefreshNow').click();await wait(async()=>(await page.locator('#opsRefreshStatus').textContent()).startsWith('已更新'));
  assert(page.url().endsWith('?page=2'));assert.equal(await page.locator('.attempt-record').count(),2);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:`${output}/detail-${width}.png`,mask:[page.locator('.hero-window h2'),page.locator('.mono'),page.locator('.submitted-answer')]});
  assert.deepEqual(errors,[]);results.push({width,passed:true,checks:['manual and 30s refresh','participant page and selection retained','draft retained','typing pause','auto toggle','failure and recovery','details expansion','detail page retained','no overflow']});
  console.log(`Refresh viewport ${width}: passed`);await context.close();
 }
 fs.writeFileSync(`${output}/results.json`,JSON.stringify(results,null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exit(1);});
