const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.QUIZ_TEST_URL;assert.equal(new URL(base).hostname,'127.0.0.1');
const fixture=JSON.parse(fs.readFileSync(process.env.QUIZ_RECORDS_FIXTURE,'utf8'));assert(fixture.syntheticOnly);
const output='output/playwright/participant-records';fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
 try{for(const user of fixture.users){
  const context=await browser.newContext({viewport:{width:user.width,height:900},isMobile:user.width<640});
  const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const screen=async name=>page.waitForFunction(name=>document.body.dataset.screen===name,name);
  const history=async()=>{await page.locator('.screen.is-active [data-open-history]').click();await screen('history');await page.waitForFunction(()=>!document.getElementById('historyRefresh').disabled);};
  const register=async data=>{await screen('register');await page.locator('[name=display_name]').fill(data.display_name);await page.locator('[name=identifier]').fill(data.identifier);await page.locator('[name=contact_type][value=email]').check();await page.locator('[name=contact]').fill(data.contact);await page.locator('#registrationSubmit').click();await screen('sections');};
  await page.goto(base+'/participant/');await page.waitForFunction(()=>window.__prototypeReady===true);await register(user);
  await history();assert.equal(await page.locator('.history-card').count(),20);
  await page.locator('#historyNext').click();await page.waitForFunction(()=>document.querySelectorAll('.history-card').length===5);
  assert((await page.locator('#historyPageStatus').textContent()).includes('共 25'));
  await page.locator('[data-history-attempt]').first().click();await screen('result');
  assert((await page.locator('#resultSaveReminder').textContent()).includes('截图保存'));
  assert((await page.locator('#resultSubmittedAt').textContent()).includes('北京时间'));
  assert.equal(await page.locator('#reviewList u').count(),1);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:`${output}/result-${user.width}.png`,fullPage:true});
  await page.locator('#resultBackToSections').click();
  const startedResponse=page.waitForResponse(r=>r.url()===base+'/api/v1/attempts' && r.request().method()==='POST');
  await page.locator('[data-category-code]').first().click();const attempt=(await (await startedResponse).json()).attempt;await screen('quiz');
  const blankIndex=attempt.questions.findIndex(q=>q.type==='fill_blank');assert(blankIndex>=0);
  await page.locator('#questionMap button').nth(blankIndex).click();await page.locator('#answerOptions input[type=text]').fill('保留草稿');
  const beforeDraft=await page.evaluate(id=>sessionStorage.getItem('ustc-nihongo-quiz:draft:'+id),attempt.id);
  await page.locator('#backToSections').click();await history();
  await page.locator('.history-card').filter({hasText:'已提交'}).first().locator('button').click();await screen('result');
  await page.locator('#resultBackToSections').click();assert(await page.locator('#resumeBanner').isVisible());
  await page.locator('#resumeAttemptButton').click();await screen('quiz');
  await page.locator('#questionMap button').nth(blankIndex).click();assert.equal(await page.locator('#answerOptions input[type=text]').inputValue(),'保留草稿');
  assert.equal(await page.evaluate(id=>sessionStorage.getItem('ustc-nihongo-quiz:draft:'+id),attempt.id),beforeDraft);
  const restored=await page.evaluate(async()=> (await (await fetch('/api/v1/attempts/current')).json()).attempt);
  assert.equal(restored.id,attempt.id);assert.equal(restored.deadline_at,attempt.deadline_at);
  await page.reload();await screen('quiz');await page.locator('#questionMap button').nth(blankIndex).click();assert.equal(await page.locator('#answerOptions input[type=text]').inputValue(),'保留草稿');
  await page.locator('#submitAttempt').click();await page.getByRole('button',{name:'确认交卷',exact:true}).click();await screen('result');
  assert((await page.locator('#resultSubmittedAt').textContent()).includes('北京时间'));
  await history();assert((await page.locator('#historyPageStatus').textContent()).includes('共 26'));
  assert.equal(await page.locator('.history-card').filter({hasText:'进行中'}).count(),0);
  const total=await page.locator('#historyPageStatus').textContent();let limited=0;
  await page.route('**/api/v1/attempts/history?*',route=>{limited++;route.fulfill({status:429,contentType:'application/json',headers:{'Retry-After':'1'},body:JSON.stringify({error:{code:'rate_limited',message:'请求较频繁',retryable:true,retry_after_seconds:1}})});});
  await page.locator('#historyRefresh').click();await page.waitForFunction(()=>document.getElementById('historyFeedback').textContent.includes('秒后重试'));
  assert.equal(limited,1);assert.equal(await page.locator('#historyPageStatus').textContent(),total);
  await page.unroute('**/api/v1/attempts/history?*');await page.locator('#historyRefresh').click();await page.waitForFunction(()=>!document.getElementById('historyRefresh').disabled);
  let release;const gate=new Promise(resolve=>release=resolve);let requested=false;
  await page.route('**/api/v1/attempts/history?*',async route=>{requested=true;await gate;await route.continue();});
  await page.locator('#historyRefresh').click();while(!requested)await new Promise(r=>setTimeout(r,20));
  await page.locator('#historyBackToSections').click();release();await page.waitForTimeout(500);assert.equal(await page.locator('body').getAttribute('data-screen'),'sections');await page.unroute('**/api/v1/attempts/history?*');
  await history();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.screenshot({path:`${output}/history-${user.width}.png`});
  await page.locator('#historyBackToSections').click();await page.locator('#clearSessionButton').click();await screen('register');
  const unauthorized=await page.evaluate(async()=> (await fetch('/api/v1/attempts/history')).status);assert.equal(unauthorized,401);
  await register(user);await history();assert((await page.locator('#historyPageStatus').textContent()).includes('共 26'));
  assert.deepEqual(errors,[]);results.push({width:user.width,passed:true,checks:['25 records pagination','historical result and save reminder','Beijing submission time','underline preserved','current blank draft and deadline retained','reload during quiz','submit and 26 records','429 no automatic replay','late response ignored after navigation','logout denies history','identity recovery restores records','no overflow']});
  console.log(`Participant records viewport ${user.width}: passed`);await context.close();
 }
 fs.writeFileSync(`${output}/results.json`,JSON.stringify(results,null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e.message);process.exit(1);});
