# Generated by Django 5.2.17 on 2026-08-25 13:30
# ruff: noqa: E501

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_key', models.SlugField(max_length=80)),
                ('pool_key', models.SlugField(max_length=80)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('fill_blank', 'Fill blank')], max_length=20)),
                ('prompt', models.TextField()),
                ('option_a', models.TextField(blank=True)),
                ('option_b', models.TextField(blank=True)),
                ('option_c', models.TextField(blank=True)),
                ('option_d', models.TextField(blank=True)),
                ('correct_option', models.CharField(blank=True, max_length=1)),
                ('acceptable_answers', models.JSONField(blank=True, default=list)),
                ('origin', models.CharField(max_length=100)),
                ('prior_event_use', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('private_event_allowed', models.BooleanField(default=True)),
                ('public_release_allowed', models.BooleanField(default=False)),
                ('source_reference', models.TextField()),
                ('source_license', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymized_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_code', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('default_question_count', models.PositiveSmallIntegerField(default=15)),
                ('default_time_limit_seconds', models.PositiveIntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('default_question_count__gt', 0)), name='activity_default_question_count_positive'), models.CheckConstraint(condition=models.Q(('default_time_limit_seconds__gt', 0)), name='activity_default_time_limit_positive')],
            },
        ),
        migrations.CreateModel(
            name='ActivityCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=100)),
                ('question_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_configs', to='quiz.activityedition')),
            ],
            options={
                'ordering': ('display_order', 'category_key'),
            },
        ),
        migrations.CreateModel(
            name='ParticipantIdentity',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='identity', serialize=False, to='quiz.participant')),
                ('display_name', models.CharField(max_length=100)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=8)),
                ('identifier_envelope', models.JSONField()),
                ('contact_envelope', models.JSONField()),
                ('identifier_digest', models.CharField(max_length=64)),
                ('contact_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='quiz.activityedition'),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='quiz.activityedition')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='quiz.participant')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PoolQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_key', models.SlugField(max_length=80)),
                ('quota', models.PositiveSmallIntegerField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('category_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_quotas', to='quiz.activitycategoryconfig')),
            ],
            options={
                'ordering': ('display_order', 'pool_key'),
            },
        ),
        migrations.CreateModel(
            name='QuestionBankVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('format_version', models.PositiveSmallIntegerField(default=1)),
                ('source_label', models.CharField(max_length=200)),
                ('content_sha256', models.CharField(max_length=64)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('version_code', 'content_sha256'), name='bank_version_content_unique')],
            },
        ),
        migrations.CreateModel(
            name='QuestionAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=500)),
                ('content_sha256', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='quiz.bankquestion')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='quiz.questionbankversion')),
            ],
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.questionbankversion'),
        ),
        migrations.CreateModel(
            name='ActivityBankActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('legacy_exception', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quiz_bank_activations', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_activations', to='quiz.activityedition')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_activations', to='quiz.questionbankversion')),
            ],
        ),
        migrations.AddField(
            model_name='bankquestion',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='quiz.questionidentity'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('timed_out', 'Timed out'), ('invalid', 'Invalid')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('deadline_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('submission_digest', models.CharField(blank=True, max_length=64)),
                ('reward_text', models.TextField(blank=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.activityedition')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.questionbankversion')),
                ('category_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.activitycategoryconfig')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quiz.participant')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryHighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('achieved_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_high_scores', to='quiz.activityedition')),
                ('category_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_scores', to='quiz.activitycategoryconfig')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_high_scores', to='quiz.participant')),
                ('source_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='high_score_records', to='quiz.quizattempt')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('option_order', models.JSONField(blank=True, default=list)),
                ('submitted_answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_items', to='quiz.bankquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quiz.quizattempt')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='RewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('max_score_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('priority', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='quiz.activityedition')),
                ('category_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='quiz.activitycategoryconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SamplingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.SlugField(max_length=80)),
                ('pool_key', models.SlugField(max_length=80)),
                ('default_quota', models.PositiveSmallIntegerField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_rules', to='quiz.questionbankversion')),
            ],
            options={
                'ordering': ('category_key', 'display_order', 'pool_key'),
            },
        ),
        migrations.AddConstraint(
            model_name='activitycategoryconfig',
            constraint=models.UniqueConstraint(fields=('activity', 'category_key'), name='activity_category_unique'),
        ),
        migrations.AddConstraint(
            model_name='activitycategoryconfig',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__isnull', True), ('question_count__gt', 0), _connector='OR'), name='category_question_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='activitycategoryconfig',
            constraint=models.CheckConstraint(condition=models.Q(('time_limit_seconds__isnull', True), ('time_limit_seconds__gt', 0), _connector='OR'), name='category_time_limit_positive'),
        ),
        migrations.AddField(
            model_name='participantidentity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_identities', to='quiz.activityedition'),
        ),
        migrations.AddConstraint(
            model_name='poolquota',
            constraint=models.UniqueConstraint(fields=('category_config', 'pool_key'), name='category_pool_quota_unique'),
        ),
        migrations.AddConstraint(
            model_name='poolquota',
            constraint=models.CheckConstraint(condition=models.Q(('quota__gt', 0)), name='category_pool_quota_positive'),
        ),
        migrations.AddConstraint(
            model_name='questionasset',
            constraint=models.UniqueConstraint(fields=('question', 'relative_path'), name='question_asset_path_unique'),
        ),
        migrations.AddConstraint(
            model_name='activitybankactivation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('activity',), name='one_current_bank_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='bankquestion',
            constraint=models.UniqueConstraint(fields=('bank', 'identity'), name='bank_question_identity_unique'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('participant',), name='one_in_progress_attempt_per_participant'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('question_count__gt', 0)), name='attempt_question_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', models.F('question_count'))), name='attempt_score_in_range'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.CheckConstraint(condition=models.Q(('deadline_at__gt', models.F('started_at'))), name='attempt_deadline_after_start'),
        ),
        migrations.AddConstraint(
            model_name='categoryhighscore',
            constraint=models.UniqueConstraint(fields=('participant', 'category_config'), name='participant_category_high_score_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'display_order'), name='attempt_item_display_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='attemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='attempt_question_unique'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_score_rate__gte', 0), ('min_score_rate__lte', 1)), name='reward_min_rate_in_range'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.CheckConstraint(condition=models.Q(('max_score_rate__gte', 0), ('max_score_rate__lte', 1)), name='reward_max_rate_in_range'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_score_rate__lte', models.F('max_score_rate'))), name='reward_rate_ordered'),
        ),
        migrations.AddConstraint(
            model_name='rewardrule',
            constraint=models.UniqueConstraint(fields=('activity', 'category_config', 'priority'), name='reward_rule_priority_unique'),
        ),
        migrations.AddConstraint(
            model_name='samplingrule',
            constraint=models.UniqueConstraint(fields=('bank', 'category_key', 'pool_key'), name='sampling_rule_pool_unique'),
        ),
        migrations.AddConstraint(
            model_name='samplingrule',
            constraint=models.CheckConstraint(condition=models.Q(('default_quota__gt', 0)), name='sampling_rule_quota_positive'),
        ),
        migrations.AddConstraint(
            model_name='participantidentity',
            constraint=models.UniqueConstraint(fields=('activity', 'identifier_digest'), name='identity_identifier_unique_per_activity'),
        ),
    ]
