# Generated by Django 5.2.17 on 2026-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityedition',
            name='is_participant_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='activityedition',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_participant_entry', True)),
                fields=('is_participant_entry',),
                name='one_participant_entry_activity',
            ),
        ),
    ]
