# Generated by Django 5.2.17 on 2026-08-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_add_participant_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityedition',
            options={'permissions': [('operate_quiz', 'Can operate the on-site quiz console')]},
        ),
    ]
