# Generated by Django 5.2.17 on 2026-08-26 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_add_operator_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(
                fields=['activity', '-created_at'], name='audit_activity_created'
            ),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(
                fields=['participant', '-created_at'], name='audit_participant_created'
            ),
        ),
        migrations.AddIndex(
            model_name='categoryhighscore',
            index=models.Index(
                fields=['activity', 'category_config', '-score', 'achieved_at'],
                name='high_score_activity_category',
            ),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(
                fields=['activity', 'created_at'], name='participant_activity_created'
            ),
        ),
        migrations.AddIndex(
            model_name='participantidentity',
            index=models.Index(
                fields=['activity', 'display_name'], name='identity_activity_display'
            ),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(
                fields=['activity', 'status', 'created_at'],
                name='attempt_act_status_created',
            ),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(
                fields=['activity', 'category_config', 'status', 'submitted_at'],
                name='attempt_act_cat_status',
            ),
        ),
    ]
