# Generated by Django 5.2.17 on 2026-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_add_ops_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("namespace", models.CharField(max_length=32)),
                ("tokens", models.DecimalField(decimal_places=6, max_digits=18)),
                ("updated_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
